const UPLOAD_SERVICE_URL = process.env.NEXT_PUBLIC_UPLOAD_SERVICE_URL;
const CONTENT_SERVICE_URL = process.env.NEXT_PUBLIC_CONTENT_SERVICE_URL;
const VTT_SERVICE_URL = process.env.NEXT_PUBLIC_VTT_SERVICE_URL;

export { UPLOAD_SERVICE_URL, CONTENT_SERVICE_URL, VTT_SERVICE_URL };
